require "utils.tableutil"
RankType = {
	LEVEL_RANK = 1,
	PET_GRADE_RANK = 9,
	FACTION_RANK = 31,
	ROLE_ZONGHE_RANK = 32,
	SINGLE_COPY_RANK1 = 21,
	SINGLE_COPY_RANK2 = 22,
	SINGLE_COPY_RANK3 = 23,
	SINGLE_COPY_RANK4 = 24,
	TEAM_COPY_RANK1 = 27,
	TEAM_COPY_RANK2 = 28,
	ROLE_RANK = 38,
	PROFESSION_WARRIOR_RANK = 43,
	PROFESSION_MAGIC_RANK = 44,
	PROFESSION_PRIEST_RANK = 45,
	PROFESSION_PALADIN_RANK = 46,
	PROFESSION_HUNTER_RANK = 47,
	PROFESSION_DRUID_RANK = 48,
	FACTION_RANK_LEVEL = 49,
	FACTION_ZONGHE = 50,
	FACTION_MC = 51,
	FACTION_NAXX = 52,
	PROFESSION_ROGUE_RANK = 60,
	PROFESSION_SAMAN_RANK = 61,
	PROFESSION_WARLOCK_RANK = 62,
	PROFESSION_PANSI_RANK = 63,
	PROFESSION_TIANGONG_RANK = 64,
	PROFESSION_WUZHUANG_RANK = 65,
	FACTION_COPY = 70,
	PVP5_LAST_GRADE1 = 81,
	PVP5_LAST_GRADE2 = 82,
	PVP5_LAST_GRADE3 = 83,
	PVP5_HISTORY_GRADE1 = 84,
	PVP5_HISTORY_GRADE2 = 85,
	PVP5_HISTORY_GRADE3 = 86,
	RED_PACK_1 = 101,
	RED_PACK_2 = 102,
	FLOWER_RECEIVE = 111,
	FLOWER_GIVE = 112,
	CLAN_FIGHT_2 = 120,
	CLAN_FIGHT_4 = 121,
	CLAN_FIGHT_WEEK = 122,
	CLAN_FIGHT_HISTROY = 123
}
RankType.__index = RankType


function RankType:new()
	local self = {}
	setmetatable(self, RankType)
	return self
end
function RankType:marshal(ostream)
	local _os_ = ostream or FireNet.Marshal.OctetsStream:new()
	return _os_
end

function RankType:unmarshal(_os_)
	return _os_
end

return RankType
